server:
  port: 80

spring:
  application:
    name: customer-order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka01:7001/eureka,http://eureka02:7002/eureka